### ISSUE TITLE
Unknown plugin "sitrep".

### ISSUE THREAD

**Issue by colshacol** [tkh44/babel-plugin-sitrep#1]
I've been waiting a full 59 minutes for you to complete this plugin, but still, any time I try it out, I get `Unknown plugin "sitrep" specificied in blah blah blah`.

What do I pay you for?!

#  (╯°□°）╯︵ ┻━┻

**Comment by tkh44** [comment]
fixed released in `babel-plugin-sitrep@1.0.1`
