### ISSUE TITLE
Use console.groupCollapsed

### ISSUE THREAD

**Issue by miraage** [tkh44/babel-plugin-sitrep#11]
console.groupCollapsed(fn.name)
...rest
console.groupEnd()

**Comment by roryokane** [comment]
Docs: [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Console/groupCollapsed), [Google](https://developers.google.com/web/tools/chrome-devtools/console/console-reference#consolegroupcollapsedobject_object), [MSDN](https://msdn.microsoft.com/en-us/library/dn265069(v=vs.85).aspx)

Looks like this is a duplicate of #8, which was already solved by a45948a9fa4dbb0200f142b2490c7bc7e0018d9b.

**Comment by miraage** [comment]
Awesome. Thanks.
