### ISSUE TITLE
Support for spread operator

### ISSUE THREAD

**Issue by kakadiadarpan** [tkh44/babel-plugin-sitrep#3]
First of all, thanks a lot for this amazing plugin. It helps a lot while debugging the code and saves a lot of time from writing manual console logs!

`const { a, b, c, d } = data;`

When I try to use spread operator as above, I get the below error

> Module build failed: TypeError: Property arguments[0] of CallExpression expected node to be of a type ["Expression","SpreadElement"] but instead got "ObjectPattern"

**Comment by tkh44** [comment]
Thanks for the issue. Could you add  PR with your code example. 

Just copy and paste this block https://github.com/tkh44/babel-plugin-sitrep/blob/2dfc02ddbeb625e17b38f8544159867ff93dbe89/src/__tests__/index.js#L47-L90 changing the title and code to match a repo case.
